### ISSUE TITLE
24th Hour mode?

### ISSUE THREAD

**Issue by invisible66** [SolomonBier/SBFlatDatePicker#4]
How can i use 24th hour mode? i mean i don't want to show "_svMeridians" :)

**Comment by SolomonBier** [comment]
Hmm, I'll add this as a feature request.

**Comment by invisible66** [comment]
i will wait :) thanks..

**Comment by SolomonBier** [comment]
@invisible66 sorry, a bit bcaked up, hopefully by end of the month

**Comment by SolomonBier** [comment]
Closed with new commit

**Comment by invisible66** [comment]
it's perfectly working. Thanks. :+1:
